### PR TITLE
fix core data thread access violation

### LINKED ISSUE #2165: Core Data Concurrency Debugging Crash
Happens when connecting a foreign key relationship, as shown in this screenshot. I am using the latest source from development.

Scheme:
`-com.apple.CoreData.ConcurrencyDebug 1`

`pod 'RestKit', git: 'https://github.com/RestKit/RestKit.git', branch: 'development'`

screen shot 2015-02-18 at 11 52 47 am

### PR DESCRIPTION
**Pull request by jeffblake**
Fixes #2165

### CODE REVIEW

**Comment by segiddins** [comment]
:+1: will merge when green, thanks!

**Comment by adly-holler** [comment]
/

File: Code/CoreData/RKRelationshipConnectionOperation.m [hunk 1]
```diff
@@ -48,11 +48,13 @@ static BOOL RKConnectionAttributeValuesIsNotConnectable(NSDictionary *attributeV
 {
     NSCAssert([connection isForeignKeyConnection], @"Only valid for a foreign key connection");
     NSMutableDictionary *destinationEntityAttributeValues = [NSMutableDictionary dictionaryWithCapacity:[connection.attributes count]];
-    for (NSString *sourceAttribute in connection.attributes) {
-        NSString *destinationAttribute = (connection.attributes)[sourceAttribute];
-        id sourceValue = [managedObject valueForKey:sourceAttribute];
-        [destinationEntityAttributeValues setValue:sourceValue ?: [NSNull null] forKey:destinationAttribute];
-    }
+    [managedObject.managedObjectContext performBlockAndWait:^{
```
Comment (Vyazovoy) [inline Code/CoreData/RKRelationshipConnectionOperation.m]: If `managedObject` has no context then `destinationEntityAttributeValues` is empty, but it pass final check. After that it will crash at line 160 because `if` statement at line 156 also mistakenly passed. I think #2217 somehow fix that, but it potentially danger approach. @jeffblake @cfis @segiddins

**Comment by cfis** [comment]
Can a managedObject not have a context?

**Comment by Vyazovoy** [comment]
"May be nil if the receiver has been deleted from its context." - official Apple docs. @cfis

**Comment by Vyazovoy** [comment]
And I find that because I have such crashes at line 160 :) I don't accidentally find this tricky bug.
